build_info:
  python_version: '3.11'

inference_compute_info:
  cpu_limit: 1000m
  cpu_memory: 1Gi
  num_accelerators: 0

model:
  app_id: mcp-examples
  id: blog_writing_search_mcp
  model_type_id: mcp
  user_id: nperla